Fixes #325 - Earthquake hazard visualization bounding box
IN-CORE/incore-services pull request #326
Opened 2024-10-28 20:47 UTC by navarroc

A bug was introduced by using the reference envelope, which expects x1, x2, y1, y2 whereas the previous expected x1, y1, width, height. This looks to fix the issue, but please check if this is correct.

2024-10-29 19:03 UTC, ywkim312 approved these changes
Code looks good. Tested by deploying this to dev instance and ran create_earthquake notebook and worked well. Using the release branch it made an error. Approve. @navarroc Should we make a hotfix release to prod soon?

2024-10-29 19:09 UTC, ywkim312 requested changes
My previous test was not done in the correct situation. Let me test one more time after fixing the dev instance

2024-10-29 19:22 UTC, ywkim312 commented
@navarroc  These are two outputs from this PR and the existing one that I got from running create_earthquake notebook
First one
```
from this PR
[{'hazardValues': [0.5322993805448739], 'demands': ['0.2 SA'], 'units': ['g'], 'loc': '35.07899, -90.0178'}, {'hazardValues': [0.502009539659276], 'demands': ['0.2 SA'], 'units': ['g'], 'loc': '35.027, -90.077'}]

from existing one
[{'hazardValues': [0.5322993805448739], 'demands': ['0.2 SA'], 'units': ['g'], 'loc': '35.07899, -90.0178'}, {'hazardValues': [0.502009539659276], 'demands': ['0.2 SA'], 'units': ['g'], 'loc': '35.027, -90.077'}]
```

Second one
```
from this PR
[{'hazardValues': [0.3779999911785126], 'demands': ['PGA'], 'units': ['g'], 'loc': '35.1322, -89.9087'}, {'hazardValues': [0.37400001287460327], 'demands': ['PGA'], 'units': ['g'], 'loc': '35.1707, -89.8417'}]

from existing one
[{'hazardValues': [0.3779999911785126], 'demands': ['PGA'], 'units': ['g'], 'loc': '35.1322, -89.9087'}, {'hazardValues': [0.37400001287460327], 'demands': ['PGA'], 'units': ['g'], 'loc': '35.1707, -89.8417'}]
```
As you can see, those outputs are identical. Maybe I did it wrong but do you have any idea?

2024-10-31 16:16 UTC, ywkim312 approved these changes
Tested and worked well. Approve

2024-10-31 19:22 UTC, ylyangtw approved these changes

2024-10-31 19:57 UTC, merged