14 add validation on delete dataset endpoint to check if there are associated hazards
IN-CORE/incore-services pull request #61
Opened 2022-01-24 21:24 UTC by diegoac2

To test, try locally deleting any dataset with the following data types (or the dataset 5f4807aa8538c817199e51ef):
* ergo:probabilisticEarthquakeRaster
* ergo:deterministicEarthquakeRaster
* incore:probabilisticTsunamiRaster
* incore:deterministicTsunamiRaster
* incore:probabilisticHurricaneRaster
* incore:deterministicHurricaneRaster
* incore:hurricaneGridSnapshot
* incore:tornadoWindfield
* incore:deterministicFloodRaster
* incore:probabilisticFloodRaster

2022-02-01 22:04 UTC, navarroc requested changes

2022-02-01 23:09 UTC, diegoac2 commented on server/data-service/src/main/java/edu/illinois/ncsa/incore/service/data/controllers/DatasetController.java
> +            throw new IncoreHTTPException(Response.Status.CONFLICT,
oooh, I see what you mean. I'll take a look

2022-02-01 23:29 UTC, diegoac2 commented on server/data-service/src/main/java/edu/illinois/ncsa/incore/service/data/controllers/DatasetController.java
> +            throw new IncoreHTTPException(Response.Status.CONFLICT,
Maybe we can remove the data type of all members that are in the orphans' space? @vnarah2 @navarroc thoughts?

2022-03-22 14:19 UTC, nunezco2 approved these changes

2023-02-24 15:33 UTC, longshuicy commented
hmm i dont think this is the right fix for the issue. Closing the PR but keep the issue.

2023-02-24 15:33 UTC, closed without merging